[features]
seeds = false
[programs.devnet]
nft_mint = "4nEddrKTzp3ZKx2KFYGV6o6uNezYQhLp6x5Nf6yAdfU5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/googo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
