[features]
seeds = false
[programs.devnet]
nft_mint = "4pVinBvRQUNvK7SaXViyUfiqHKLP2bB1FhtMy18MH3th"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/googo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
